### ISSUE TITLE
any way to set dest directory?

### ISSUE THREAD

**Issue by ttback** [jsoverson/grunt-preprocess#35]
Is it possible to preprocess all files from src to a dest directory? currently i have to do a copy task in order to make this happen.

**Comment by joshq00** [comment]
here's an example to preprocess many. Maybe this can be added to the README
```javascript
grunt.initConfig( {
	preprocess: {
		html: {
			src: '**/*.tmpl',
			ext: '.html',
			cwd: 'src',
			dest: 'build',
			expand: true
		},
		js: {
			src: 'js/**/*.js',
			cwd: 'src',
			dest: 'build',
			expand: true
		}
	}
} );
```

This configuration will take my project
```
.
|-- src
|   |-- js
|   |   |-- app.js
|   |   |-- config.js
|   |   |-- routes.js
|   |   `-- services.js
|   |-- views
|   |   `-- app.tmpl
|   |-- footer.tmpl
|   |-- header.tmpl
|   `-- layout.tmpl
|-- gruntfile.js
`-- package.json
```

and generate
```
.
`-- build
    |-- js
    |   |-- app.js
    |   |-- config.js
    |   |-- routes.js
    |   `-- services.js
    |-- views
    |   `-- app.html
    |-- footer.html
    |-- header.html
    `-- layout.html
```

**Comment by lvl-svasseur** [comment]
@joshq00 is it supported already or is it more a suggestion you did here?  It's not quite clear here as the issue is not closed and @jsoverson said it's not possible yet.

**Comment by joshq00** [comment]
The configuration I posted is functional

**Comment by BendingBender** [comment]
@joshq00 Thank you for the information! Added your config as example to readme.
