### ISSUE TITLE
preprocess inside <script> tag on an HTML

### ISSUE THREAD

**Issue by nescalante** [jsoverson/grunt-preprocess#45]
Actually this code inside an `index.html` file is not working for me:

```html
<div>text, tags, and moar moar things</div>
<script>
// @echo SOME_KEY
moarJsCode();
</script>
```

with this configuration on the Gruntfile:

```js
preprocess: {
  options: {
    context: { SOME_KEY: 'var foo="bar"' }
  }
}
```

am I missing something? is it possible to parse js inside a tag in an html?

**Comment by BendingBender** [comment]
I'm afraid that at the moment only html-style comment blocks are supported inside of an html file. You could however create a separate js file, add preprocess annotations there and use `@include` in the html file to inline the js file into a script tag.

**Comment by nescalante** [comment]
Actually, this works in an HTML file:

```html
<script>
var key = '<!-- @echo SOME_KEY -->';
doSomethingWithThat(key);
</script>
```

so, temporary solved on that way.

**Comment by BendingBender** [comment]
Ok, I thought you were using directives like `@if` or the like. It would be harder to hide them inside of js code with only html comments at hand..
