### ISSUE TITLE
Lacks on documentation.

### ISSUE THREAD

**Issue by dadoz** [jsoverson/grunt-preprocess#46]
Hello.
We got some problems due on lacks on documentation.
Here down I'll list you all the problems that takes me 5 hours of swears:
- on HTML side the rule  doesn't work. 
  Instead the one wrapped with spaces it works well.
- on HTML the OR,AND condition (on if statement) is never mentioned.

Please take a look at doc and fix it as well.
Davide

**Comment by BendingBender** [comment]
Moved issue to jsoverson/preprocess.
